name: Deploy Astro Site to GitHub Pages

on:
  push:
    branches: ["astro"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./astro
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: "./astro/pnpm-lock.yaml"

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright
        run: pnpm exec playwright install chromium

      - name: Build with Astro
        run: pnpm run build
        
      - name: Start Astro Preview Server
        run: |
          pnpm run preview -- --host 0.0.0.0 --port 3000 &
          echo $! > astro-server.pid
          # Give the server some time to start
          sleep 10
        shell: bash

      - name: Generate PDF from CV
        run: pnpm run generate-pdf
        env:
          CV_URL: "http://localhost:3000/cv"

      - name: Stop Astro Server
        run: |
          if [ -f astro-server.pid ]; then
            kill $(cat astro-server.pid) || true
            rm astro-server.pid
          fi
        shell: bash
        if: always()
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./astro/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
